// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8K7vUJFoO9LJjJBfALvgMnDVFhhd6xho',
    appId: '1:233173649214:web:fdabb871d9da3cbe6c0e6f',
    messagingSenderId: '233173649214',
    projectId: 'basic-calculator237',
    authDomain: 'basic-calculator237.firebaseapp.com',
    storageBucket: 'basic-calculator237.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ82UC8MsiM8FymBaUMKs8iwOoQQpNpok',
    appId: '1:233173649214:android:46781652c3d9a1a66c0e6f',
    messagingSenderId: '233173649214',
    projectId: 'basic-calculator237',
    storageBucket: 'basic-calculator237.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsuTc3bvGVHItSDtwI72dd5W4FCVDaKcI',
    appId: '1:233173649214:ios:26f26c4ac588173d6c0e6f',
    messagingSenderId: '233173649214',
    projectId: 'basic-calculator237',
    storageBucket: 'basic-calculator237.firebasestorage.app',
    iosBundleId: 'com.example.basicCalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8K7vUJFoO9LJjJBfALvgMnDVFhhd6xho',
    appId: '1:233173649214:web:b4ecf2026308c1616c0e6f',
    messagingSenderId: '233173649214',
    projectId: 'basic-calculator237',
    authDomain: 'basic-calculator237.firebaseapp.com',
    storageBucket: 'basic-calculator237.firebasestorage.app',
  );
}
